c Include file for contact version 8.x

      parameter (maxat = 500000)
      parameter (maxat2 = 10000)
      parameter (maxnumatomtypes=20)
      parameter (maxnumatomtypesEnv = 4)
      parameter (maxnumatomtypesTop = 8)
      parameter (maxdatalines = 300)
      parameter (numrestypes=20)
      parameter (pi = 3.14159)
	  parameter (pmfStep = 0.2)
      parameter (BinsInHistogram = 25)
      parameter (maxNumCoord = 15)
      parameter (maxMaxNumCoord = 50)
      parameter (maxNumRes = 50000)
      parameter (numCoord = 14)
      parameter (maxnumdistances = 100)
      parameter (maxNumPDBs = 2000)
      parameter (maxnumcomments = 1800)
      parameter (maxnumtrans = 60)
      parameter (pmfMaxNumBins = 300)
      parameter (S = 0.020)
      parameter (RT = 0.582)
      parameter (mapEnd = 2381)
